//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class commentMasterClient
    {
        public int commentID { get; set; }
        public int requestID { get; set; }
        public int masterID { get; set; }
    
        public virtual comment comment { get; set; }
        public virtual request request { get; set; }
    }
}
